declare module 'react-native-ico-material-design' {
    import { ReactNode } from 'react';
    import { SvgProps } from 'react-native-svg';

    type AdditionalProps = {
      onError?: (error: Error) => void;
      onLoad?: () => void;
      fallback?: ReactNode;
    };

    type iconNames = 'closed-caption-logo' |
      'developer-mode-for-smartphones-and-tablets' |
      'film-roll' |
      'screen-rotation-lock-button' |
      'brochure-with-three-sections' |
      'drop-down-arrow' |
      'users-social-symbol' |
      'clapperboard' |
      'google-symbol' |
      'play-button-inside-a-circle' |
      'report-symbol' |
      'bluetooth-searching-signal-indicator' |
      'cloud-download' |
      'bluetooth-disabled-button' |
      'set-timer-button' |
      'tag-button-with-happy-face' |
      'failed-sms' |
      'bug-report-button' |
      'window-with-different-sections' |
      'memory-chip' |
      'blank-square' |
      'refresh-button-1' |
      'caps-lock-button-1' |
      'tablet-with-blank-screen' |
      'car-changing-lanes' |
      'drafts-evelope-button' |
      'end-call-button' |
      'public-transport-subway' |
      'full-screen-exit' |
      'left-arrow-missed-call' |
      'puzzle-piece-plugin' |
      'blueetooth-logo' |
      'expand-arrow' |
      'camera-diaphragm' |
      'round-pause-button' |
      'ring-volume-control-button' |
      'black-envelope-email-symbol' |
      'light-bulb-on' |
      'man-cycling' |
      'round-data-usage-symbol' |
      'shining-rectangular-object' |
      'bluetooth-connected' |
      'notifications-button' |
      'linkedin-logo' |
      'planet-earth' |
      'google-apps-script-logo' |
      'microphone-voice-button' |
      'world-shape-public-symbol' |
      'black-check-box-with-white-check' |
      'gps-location-disabled' |
      'cell-phone-vibration' |
      'user-inside-bubble-speech' |
      'waving-flag' |
      'share-button' |
      'emoticon-with-happy-face' |
      'filled-circle' |
      'google-plus-logo-on-black-background' |
      'website-with-different-sections' |
      'crop-tool-button' |
      'fast-forward-button' |
      'bookmark-button-1' |
      'two-rows-and-three-columns-layout' |
      'add-button-inside-black-circle' |
      'enter-arrow' |
      'round-delete-button' |
      'device-connected-1' |
      'help-round-button' |
      'create-group-button' |
      'screen-locked' |
      'google-drive-document' |
      'merge-calls-arrow' |
      'play-slideshow-button' |
      'compass-with-white-needles' |
      'laptop-outline' |
      'usb-symbol' |
      'random-line' |
      'visibility-button' |
      'wifi-signal-waves' |
      'phone-settings' |
      'clapperboard-1' |
      'smartphone-with-three-buttons' |
      'turn-synchronization-off' |
      'cell-phone-high-signal-indicator' |
      'sim-card-problem' |
      'three-dots-more-indicator' |
      'connection-indicator' |
      'google-plus-logo' |
      'videocall-button' |
      'hide-keyboard-button' |
      'wifi-low-signal-with-one-bar' |
      'link-button' |
      'insert-picture-button' |
      'chemistry-polymer' |
      'schedule-button' |
      'rounded-info-button' |
      'workspace-with-two-horizontal-windows' |
      'half-filled-rating-star' |
      'favorite-heart-button' |
      'panoramic-mountain-photography' |
      'circle-outline' |
      'credit-card' |
      'printer-printing-document' |
      'set-alarm' |
      'up-arrow-key' |
      'verification-mark' |
      'phone-call-button' |
      'gps-fixed-indicator' |
      'photo-frame' |
      'attachment-clip' |
      'sort-button-with-three-lines' |
      'gps-off' |
      'clock-with-white-face' |
      'add-label-button' |
      'synchronization-problem' |
      'mark-as-unread-envelope-button' |
      'keyboard-right-arrow-button-1' |
      'sd-card-1' |
      'device-connected' |
      'notifications-bell-button' |
      'car-directions' |
      'list-button-with-3-elements' |
      'rounded-add-button-1' |
      'download-button' |
      'phone-receiver-with-bluetooth-sign' |
      'dark-cloud' |
      'email-inbox' |
      'import-export-arrows' |
      'headset-with-microphone' |
      'turn-visibility-off-button' |
      'new-tab-button' |
      'favorite-heart-outline-button' |
      'history-clock-button' |
      'unlocked-padlock' |
      'wifi-high-signal' |
      'black-keyboard-with-white-keys' |
      'download-button-1' |
      'shopping-basket-button' |
      'sms-bubble-speech' |
      'round-remove-button' |
      'turn-airplane-mode-off' |
      'cut-content-button' |
      'mountain-range-on-black-background' |
      'chat-bubbles' |
      'flash-off' |
      'mountains-inside-a-circle' |
      'show-less-fold-button' |
      'rounded-add-button' |
      'sms-speech-bubble' |
      'google-drive-file' |
      'smartphone-dock' |
      'sd-card' |
      'show-more-button-with-three-dots' |
      'google-hangouts-logo' |
      'screen-rotation-button' |
      'downwards-arrow-key' |
      'swap-vertical-orientation-arrows' |
      'screen-with-rounded-corners' |
      'go-back-left-arrow' |
      'android-logo-1' |
      'upload-button' |
      'left-arrow-key' |
      'https-symbol' |
      'shuffle-mode-arrows' |
      'play-rounded-button' |
      'settings-cogwheel-button' |
      'play-arrow' |
      'telephone-keypad-with-ten-keys' |
      'google-plus-party-mode' |
      'nfc-near-field-communication' |
      'brightness-control' |
      'medium-signal' |
      'work-briefcase' |
      'gamepad-1' |
      'web-server' |
      'write-email-envelope-button' |
      'drop-down-round-button' |
      'medium-brightness-cogwheel' |
      'folder-symbol' |
      'notifications-silenced' |
      'call-received-arrow' |
      'user-account-box' |
      'new-tab' |
      'watch-with-blank-face' |
      'auto-white-balance' |
      'show-menu-button' |
      'tack-save-button' |
      'high-wifi-signal-indicator' |
      'check-symbol' |
      'mouse-filled-tool' |
      'locked-padlock-outline' |
      'bookmark-button' |
      'shining-sun' |
      'select-all' |
      'horizontal-line-remove-button' |
      'blogger-logo' |
      'instagram-logo' |
      'add-to-queue-button' |
      'rounded-remove-button' |
      'add-comment-button' |
      'bed-quilt' |
      'invert-colors-button' |
      'videocam-filled-tool' |
      'user-account-box-1' |
      'rewind-button' |
      'forward-arrow' |
      'good-wifi-signal-with-three-bars' |
      'searching-location-gps-indicator' |
      'check-box' |
      'shopping-cart' |
      'circle-with-check-symbol' |
      'turn-notifications-off-button' |
      'switch-video-on' |
      'black-plane' |
      'tick-inside-circle' |
      'map-placeholder' |
      'home-button' |
      'drop-up-arrow' |
      'record-voice-microphone-button' |
      'two-men' |
      'framed-portrait' |
      'painter-palette' |
      'voice-message-microphone-button' |
      'thumb-up-button' |
      'forward-right-arrow-button' |
      'photo-library' |
      'google-drive-folder-symbol' |
      'phone-paused-indicator' |
      'google-cast-logo' |
      'round-account-button-with-user-inside' |
      'snake-game' |
      'show-more-button' |
      'switch-camera-button' |
      'apple-accessibility' |
      'move-window' |
      'show-apps-button' |
      'traffic-light' |
      'tumblr-logo' |
      'chat-bubble' |
      'medium-wifi-signal-with-two-bars' |
      'adjust-button-with-plus-and-minus' |
      'square-add-button' |
      'phone-locked' |
      'turn-microphone-off-button' |
      'youtube-logo' |
      'photo-album' |
      'previous-track' |
      'high-signal-indicator' |
      'cloud-symbol-inside-a-circle' |
      'circumference' |
      'reminder-bow' |
      'round-error-symbol' |
      'google-drive-image' |
      'automatic-brightness' |
      'two-circles-one-inside-the-other' |
      'pages-of-google-plus' |
      'circles-extend-button' |
      'replay-arrow' |
      'public-transport-train-directions' |
      'save-button' |
      'list-of-three-elements-on-black-background' |
      'rounded-pause-button' |
      'add-alarm-button' |
      'filled-speaker-with-white-details' |
      'power-connection-indicator' |
      'virtual-private-network-vpn-symbol' |
      'read-more-left-arrow-button' |
      'filled-cloud' |
      'rate-star-button' |
      'poll-symbol-on-black-square-with-rounded-corners' |
      'earth-grid-select-language-button' |
      'underline-button' |
      'high-quality-button' |
      'ellipsis' |
      'user-outline' |
      'man-walking-directions-button' |
      'city-buildings-silhouette' |
      'pinterest-logo' |
      'get-directions-button' |
      'send-button' |
      'keyboard-left-arrow-button' |
      'automatic-flash-symbol' |
      'screen-locked-1' |
      'black-check-box' |
      'volume-off-indicator' |
      'left-arrow-key-1' |
      'black-bubble-speech' |
      'button-on' |
      'blank-check-box' |
      'twitter-logo-on-black-background' |
      'microphone-of-voice' |
      'bubble-speech-with-three-lines' |
      'android-logo' |
      'call-forwarding' |
      'round-info-button' |
      'burn-button' |
      'searching-magnifying-glass' |
      'parking-sign' |
      'warning-sign' |
      'tab-symbol' |
      'settings-cogwheel-inside-black-square' |
      'google-glass-logo' |
      'clipboard-paste-button' |
      'mountain-range' |
      'cell-phone-with-blank-screen' |
      'close-button' |
      'plus-one' |
      'location-arrow' |
      'turn-video-off-button' |
      'hotel-with-three-floors' |
      'copy-content' |
      'add-plus-button' |
      'voicemail' |
      'hangouts-videocall-button' |
      'add-user-button' |
      'google-drive-fusion-tables-logo' |
      'stop-button' |
      'front-store' |
      'send-to-back-button' |
      'volume-muted' |
      'flash-on-indicator' |
      'train-public-transport' |
      'send-to-front-button' |
      'screen-with-news-sections' |
      'google-drive-spreadsheet' |
      'bluetooth-settings' |
      'camera' |
      'expand-button' |
      'low-signal-indicator' |
      'keyboard-right-arrow-button' |
      'gamepad' |
      'thumb-down-button' |
      'bookmark-outline' |
      'briefcase-with-tick-inside' |
      'thermostat-temperature-wheel' |
      'underline-text-button' |
      'mark-as-favorite-star' |
      'cancel-button' |
      'round-add-button' |
      'front-bus' |
      'clear-button' |
      'split-call-arrows' |
      'gps-location-symbol' |
      'crop-button' |
      'backspace-arrow' |
      'birthday-cake' |
      'undo-button' |
      'rotate-to-right-button' |
      'cloud-done-symbol' |
      'download-to-smartphone' |
      'call-made-right-arrow' |
      'bookmark-ribbon' |
      'map-symbol' |
      'back-arrow' |
      'double-tick-indicator' |
      'been-here-marker' |
      'cloud-off' |
      'google-chrome-logo-filled-with-white-colour' |
      'car-front' |
      'problems-with-synchronization' |
      'locked-padlock' |
      'radio-on-button' |
      'headset' |
      'play-next-button' |
      'exit-to-app-button' |
      'synchronization-arrows' |
      'switch-vertical-orientation-arrows' |
      'user-shape' |
      'change-power-options' |
      'blank-frame' |
      'progress-indicator' |
      'good-mood-emoticon' |
      'cloud-backup-up-arrow' |
      'synchronization-button-with-two-arrows' |
      'rotate-to-left-button' |
      'volume-down-indicator' |
      'cloud-outline' |
      'reply-all-button' |
      'turn-notifications-on-button' |
      'landscape-with-mountains' |
      'photographic-film-roll' |
      'disc-is-full' |
      'label-right-arrow-outline' |
      'rubbish-bin-delete-button' |
      'microsoft-excel-logo' |
      'airplane-mode-on-symbol' |
      'view-list-button' |
      'google-hangouts-turn-video-off' |
      'help-button-speech-bubble-with-question-mark' |
      'filter-results-button' |
      'speech-bubble-with-mountains-inside' |
      'server-rack-with-three-levels' |
      'select-brightness-button' |
      'swap-horizontal-orientation-arrows' |
      'facebook-logo' |
      'pause-button' |
      'briefcase-download-button-with-downwards-arrow' |
      'menu-button' |
      'graduate-cap' |
      'gmail-logo' |
      'rounded-block-sign' |
      'google-drive-presentation' |
      'magic-wand-auto-fix-button' |
      'refresh-button' |
      'time-lapse' |
      'receipt' |
      'bluetooth-signal-indicator' |
      'volume-up-indicator' |
      'switch-to-full-screen-button' |
      'do-not-disturb-rounded-sign' |
      'microsoft-word-logo' |
      'phone-working-indicator' |
      'front-car' |
      'google-drive-logo' |
      'right-arrow-forward' |
      'shared-folder' |
      'google-drive-pdf-file' |
      'round-rgb-button' |
      'upload-to-cloud-button' |
      'missed-call-phone-receiver-with-left-arrow' |
      'three-columns-layout' |
      'caps-lock-button' |
      'rounded-adjust-button-with-plus-and-minus' |
      'create-new-pencil-button';

    type iconColors = ;

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors?: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
